[project]
name = "scrapyard_backend"
version = "2.3.0"
description = ""
authors = [
    { name = "gchristnsn", email = "gchristnsn@gmail.com" }
]
requires-python = ">=3.7"

dependencies = [
    "Flask==3.0.3",
    "beautifulsoup4==4.12.3",
    "regex==2024.9.11"
]

[project.optional-dependencies]
server = [
    "gunicorn>=22.0.0; sys_platform != 'win32'",
    "flask-sock>=0.7.0",
    "python-dotenv>=1.0.0",
    "cryptography>=42.0.0"
]

[project.scripts]
scrapyard_backend = "scrapyard.backend:main"
scrapyard_server = "scrapyard.server_main:main"

[tool.setuptools.package-data]
"scrapyard" = ["resources/*", "resources/*/*"]

[tool.setuptools.packages]
find = { include = ["scrapyard*"] }
